export default {

    RESET : 'RESET',
    HARD_RESET : 'HARD_RESET',
    UPDATE_ID :' UPDATE_ID',
    FOLLOW_RECIPE : 'FOLLOW_RECIPE',
    REMOVE_DUPLICATE : 'REMOVE_DUPLICATE',
    FETCH_DATA: 'FETCH_DATA'
  };